#pragma config(Sensor, dgtl1,  ArmEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           clawLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftLeftMiddle, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRightTop,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driveRight2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          clawRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void forwardFour(int pwr, int degs)
//{
//	SensorValue[frontRightE] = 0;
//	while (abs(SensorValue[frontRightE]) <= degs)//This is were you may need to swich the < to a > and possibly the degs to -degs if it doesnt work.
//	{
//		motor[frontRight] = pwr;
//		motor[frontLeft] = pwr;
//		motor[backRight] = pwr;
//		motor[backLeft] = pwr;
//	}
//	motorsOff();
//}




task main()
{

	const int maxPower = 127; //max power of vex motors
	float powerPercent = 1; //var to set power to the bot
	float power = 0; //power to write to motors

	int armMotor;
	int forwardVal;

	bool fwd = false;
	bool bwd = false;

	char encoderVal[15];
	char powerVal[15];

	bool fwdJoyTog = false;

	bool spinJoyTog = false;
	bool leftSpin = false;
	bool rightSpin = false;

	bool armTog = false;
	bool upArm = false;
	bool downArm = false;

	bool clawTog = false;
	bool openClaw = false;
	bool closeClaw = false;

	while (true)
	{
		// this allows the partner controller to control power. Maybe not needed? Maybe you always go MAXIMUM POWER
		if (vexRT[Btn7UXmtr2] == 1)
		{
			powerPercent = 0.1;
		}
		if (vexRT[Btn7LXmtr2] == 1)
		{
			powerPercent = 0.2;
		}
		if (vexRT[Btn7DXmtr2] == 1)
		{
			powerPercent = 0.3;
		}
		if (vexRT[Btn7RXmtr2] == 1)
		{
			powerPercent = 0.4;
		}
		if (vexRT[Btn8UXmtr2] == 1)
		{
			powerPercent = 0.5;
		}
		if (vexRT[Btn8LXmtr2] == 1)
		{
			powerPercent = 0.6;
		}
		if (vexRT[Btn8DXmtr2] == 1)
		{
			powerPercent = 0.7;
		}
		if (vexRT[Btn8RXmtr2] == 1)
		{
			powerPercent = 0.8;
		}
		if (vexRT[Btn5UXmtr2] == 1)
		{
			powerPercent = 0.9;
		}
		if (vexRT[Btn6UXmtr2] == 1)
		{
			powerPercent = 1.0;
		}
		power = powerPercent*maxPower;


		if (vexRT[CH3] >= 10)//Adds a threshold of +10 to set values
			{
				fwdJoyTog = true;
				fwd = true;

				forwardVal = power; //sets + joy values to variables
			}
		else if (vexRT[CH3] <= -10)//Adds a threshold of -10 to set values
		{
			fwdJoyTog = true;
			bwd = true;
			forwardVal = -power; //sets - joy values to variables
		}
		else
		{
			if (fwdJoyTog == false)
			{
				if(spinJoyTog == false)
				{
					SensorValue[RightEncoder] = 0;
				}
			}

			else {

				if (fwd == true)// meaning the bot went forward
				{
					sprintf(encoderVal, "%d", abs(SensorValue[RightEncoder]));
					sprintf(powerVal, "%d", power);

					writeDebugStream("forwardFour(");
					writeDebugStream(powerVal);
					writeDebugStream(",");
					writeDebugStream(encoderVal);
					writeDebugStreamLine(");");

					fwd = false;
					fwdJoyTog = false;
				}

				else {

					sprintf(encoderVal, "%d", abs(SensorValue[RightEncoder]));
					sprintf(powerVal, "%d", power);

					writeDebugStream("backwardFour(");
					writeDebugStream(powerVal);
					writeDebugStream(",");
					writeDebugStream(encoderVal);
					writeDebugStreamLine(");");

					bwd = false;
					fwdJoyTog = false;
				}
			}
			forwardVal = 0;
		}



		motor[driveLeft] = forwardVal;
		motor[driveRight2] = -forwardVal;
	}


}
